### ISSUE TITLE
hey can you pass me the pdfs folder , you ignored in your .gitignore? email in issue body

### ISSUE THREAD

**Issue by ManishPoudel** [abhigyan7/vis-odom#1]
wanted to learn these stuffs so pdf or links would help.
poudelmanish321@gmail.com

**Comment by abhigyan7** [comment]
Turns out I've deleted the folder but I remember having the ORB-SLAM, PTAM, LSD-SLAM papers in there. I also had Bundle Adjustment: A Modern Synthesis and the Multiple View Geommetry.

**Comment by ManishPoudel** [comment]
Very nice thanks.
